version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "3030:3030"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - prisma
      - postgres
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "5555:5555"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
volumes:
  postgres: ~
