version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    container_name: prisma
    links:
      - postgres
    ports:
      - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    build: ./backend
    container_name: backend
    links:
      - prisma
      - postgres
    # ports:
    #   - "3030:3030"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - prisma
      - postgres
    environment:
      - FRONTEND_URL="http://localhost:3050/"
  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    # ports:
    #   - "5555:5555"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    environment:
      - GRAPHQL_URL="http://localhost:3050/api"
volumes:
  postgres: ~
